name: Flutter build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk
          retention-days: 5

  web-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build web
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
          retention-days: 5
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web

  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle
          retention-days: 5

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release
          retention-days: 5

  ios-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios
          path: build/ios/iphoneos/Runner.app
          retention-days: 5

  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release
          retention-days: 5
